version: '3'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./DockerFile
    ports:
      - 9999:80
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - /board_game_database/data:/data/db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:dragonshoard.local:27017/
      ME_CONFIG_BASICAUTH: false